train:
  _target_: fastspeech2.datasets.RUSLANFeatureDataset

  features_dir: data/features
  metadata_path: data/metadata_RUSLAN_22200.csv

  vocabulary_path: data/phoneme_vocab.json
  emotion_labels_path: "data/emotion_labels_hf_test.json"

  instance_transforms: null

  max_samples: 4

val:
  _target_: fastspeech2.datasets.RUSLANFeatureDataset

  features_dir: data/features
  metadata_path: data/metadata_RUSLAN_22200.csv

  vocabulary_path: data/phoneme_vocab.json
  emotion_labels_path: "data/emotion_labels_hf_test.json"

  instance_transforms: null

  max_samples: 4
