_target_: fastspeech2.logger.CometMLWriter
project_name: "tts-project"
workspace: null
api_key: null
run_id: null
run_name: "fastspeech2_training"
mode: "online"
save_code: false
log_checkpoints: false
id_length: 32

loss_names: ["loss", "mel_loss", "duration_loss", "pitch_loss", "energy_loss", "emotion_loss"]

log_spectrograms: true
log_pitch: true
log_energy: true
log_duration: true
log_audio: false
log_frequency: 50
