_target_: fastspeech2.logger.WandBWriter
project_name: "fastspeech2-russian"
entity: null
run_name: "fastspeech2_training"
mode: "online"
save_code: true
log_checkpoints: true
id_length: 8

loss_names: ["loss", "mel_loss", "duration_loss", "pitch_loss", "energy_loss"]

log_spectrograms: true
log_pitch: true
log_energy: true
log_duration: true
log_audio: false
log_frequency: 50
