_target_: fastspeech2.models.FastSpeech2

vocab_size: 89

d_model: 384
encoder_layers: 6
decoder_layers: 6
num_heads: 4
d_ff: 1536
dropout: 0.2

n_mels: 80

max_seq_len: 5000

n_bins: 256

pitch_min: 80.0
pitch_max: 400.0
pitch_stats_path: "data/pitch_stats.json"

energy_min: 0.0
energy_max: 1.0
